//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conta
    {
        public int Id { get; set; }
        public Nullable<int> CorrentistaId { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<System.DateTime> DataAbertura { get; set; }
    }
}
