//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correntista
    {
        public int Id { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
    }
}
