//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamento
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> ContaId { get; set; }
        public string Operacao { get; set; }
        public string Historico { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
